### ISSUE TITLE
Implement Caching

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/lyric-api#2]

**Comment by ohnx** [comment]
Alternatively, you could just set up a CDN to cache the website for you.

**Comment by rhnvrm** [comment]
Hi, could you please elaborate? I've never used CDN before. I just tried to setup on Cloudfare and it said that I can't enter a subdomain like mine is.

**Comment by ohnx** [comment]
A CDN helps take load off of your server. Services like Cloudflare can cache static files (HTML, CSS, JS) to reduce the number of requests sent to your server.

I could try to explain how Cloudflare works, but [the CEO does it better here](https://www.quora.com/How-does-CloudFlare-work).

In the case of this, since lyrics to songs rarely ever change, you could have a permanently cached version of the page in the CDN. After the first request, no more requests will ever be sent to your server for the same song.

**Comment by rhnvrm** [comment]
I've tried once again and the only way it seems is to enter my credit card info. Do you know of any other free alternatives?

**Comment by ohnx** [comment]
Sorry! I just noticed your reply...
When adding a website to CloudFlare, you can select a "Free" tier account, which shouldn't require your credit card information.
